apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-martin-to-db
  namespace: jku-cloud-computing
spec:
  podSelector:
    matchLabels:
      app: martin-server
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgresql
      ports:
      - protocol: TCP
        port: 5432