apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: jku-cloud-computing
spec:
  rules:
  # - host: app.bestmapfiles.jku.cloud.com
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: frontend-service
  #           port:
  #             number: 80
  - host: api.bestmapfiles.jku.cloud.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: martin-service
            port:
              number: 80
